/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.sms.view;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author Chamini
 */
public class AddStudentForm extends javax.swing.JFrame {

    /**
     * Creates new form AddStudentForm
     * @param view
     */
    
    public AddStudentForm() {
    }

    public AddStudentForm(String view) {
        initComponents();
        setDate();
       setFullSreen();
        if (view.equals("Add Student")) {
            btnAStudent.doClick();
        }else if(view.equals("View Profile")){
            btnVProfile.doClick();
        }else if(view.equals("Exams")){
            btnExams.doClick();
        }else if(view.equals("Attendense")){
            btnAttendance.doClick();
        }else if(view.equals("Payment")){
            btnPayments.doClick();
        }else if(view.equals("Teacher")){
            btnTeacher.doClick();
        }else if(view.equals("Reports")){
            btnReports.doClick();
        }
//        btnAStudent.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DAteOn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelAsian = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnVProfile = new javax.swing.JButton();
        btnAStudent = new javax.swing.JButton();
        btnExams = new javax.swing.JButton();
        btnAttendance = new javax.swing.JButton();
        btnPayments = new javax.swing.JButton();
        btnTeacher = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 38)); // NOI18N
        jLabel3.setText("Welcom To ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(630, 10, 220, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 38)); // NOI18N
        jLabel4.setText("Asian Higher Educational Center");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(460, 50, 600, 50);

        DAteOn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(DAteOn);
        DAteOn.setBounds(1120, 40, 190, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 0, 160, 110);

        javax.swing.GroupLayout panelAsianLayout = new javax.swing.GroupLayout(panelAsian);
        panelAsian.setLayout(panelAsianLayout);
        panelAsianLayout.setHorizontalGroup(
            panelAsianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        panelAsianLayout.setVerticalGroup(
            panelAsianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        jPanel1.add(panelAsian);
        panelAsian.setBounds(190, 130, 1170, 630);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        btnVProfile.setBackground(new java.awt.Color(0, 51, 102));
        btnVProfile.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnVProfile.setForeground(new java.awt.Color(204, 204, 204));
        btnVProfile.setText("View Profile");
        btnVProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVProfileActionPerformed(evt);
            }
        });

        btnAStudent.setBackground(new java.awt.Color(0, 51, 102));
        btnAStudent.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnAStudent.setForeground(new java.awt.Color(204, 204, 204));
        btnAStudent.setText("Add Student");
        btnAStudent.setInheritsPopupMenu(true);
        btnAStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAStudentActionPerformed(evt);
            }
        });

        btnExams.setBackground(new java.awt.Color(0, 51, 102));
        btnExams.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnExams.setForeground(new java.awt.Color(204, 204, 204));
        btnExams.setText("Exams");
        btnExams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExamsActionPerformed(evt);
            }
        });

        btnAttendance.setBackground(new java.awt.Color(0, 51, 102));
        btnAttendance.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnAttendance.setForeground(new java.awt.Color(204, 204, 204));
        btnAttendance.setText("Attendance");
        btnAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttendanceActionPerformed(evt);
            }
        });

        btnPayments.setBackground(new java.awt.Color(0, 51, 102));
        btnPayments.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnPayments.setForeground(new java.awt.Color(204, 204, 204));
        btnPayments.setText("Payments");
        btnPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentsActionPerformed(evt);
            }
        });

        btnTeacher.setBackground(new java.awt.Color(0, 51, 102));
        btnTeacher.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnTeacher.setForeground(new java.awt.Color(204, 204, 204));
        btnTeacher.setText("Teacher");
        btnTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherActionPerformed(evt);
            }
        });

        btnReports.setBackground(new java.awt.Color(0, 51, 102));
        btnReports.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnReports.setForeground(new java.awt.Color(204, 204, 204));
        btnReports.setText("Reports");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPayments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExams, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTeacher, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(164, 164, 164))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnAStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExams, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 130, 180, 640);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/power.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1320, 10, 25, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1366, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1368, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        DashboadForm DF=new DashboadForm();
        DF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnVProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVProfileActionPerformed
        // TODO add your handling code here:
    panelAsian.removeAll();
    panelAsian.repaint();
    panelAsian.revalidate();
    ViewProfileForm VF=new ViewProfileForm();
    VF.setSize(panelAsian.getSize());
    panelAsian.add(VF);
    panelAsian.repaint();
    panelAsian.revalidate();
            
    }//GEN-LAST:event_btnVProfileActionPerformed

    private void btnAStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAStudentActionPerformed
        // TODO add your handling code here:
        panelAsian.removeAll();
        panelAsian.repaint();
        panelAsian.revalidate();
        RegistrationForm AS = new RegistrationForm();
       AS.setSize(panelAsian.getSize());
       panelAsian.add(AS);
       panelAsian.repaint();
       panelAsian.revalidate();

    }//GEN-LAST:event_btnAStudentActionPerformed

    private void btnExamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExamsActionPerformed
        // TODO add your handling code here:
        panelAsian.removeAll();
        panelAsian.repaint();
        panelAsian.revalidate();
        ExamsForm EF=new ExamsForm();
        EF.setSize(panelAsian.getSize());
        panelAsian.add(EF);
        panelAsian.repaint();
        panelAsian.revalidate();
                
       
    }//GEN-LAST:event_btnExamsActionPerformed

    private void btnAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttendanceActionPerformed
        // TODO add your handling code here:
      panelAsian.removeAll();
      panelAsian.repaint();
      panelAsian.revalidate();
      AttendanceForm AtF=new AttendanceForm();
      AtF.setSize(panelAsian.getSize());
      panelAsian.add(AtF);
      panelAsian.repaint();
      panelAsian.revalidate();
              
    }//GEN-LAST:event_btnAttendanceActionPerformed

    private void btnPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentsActionPerformed
        // TODO add your handling code here:
       panelAsian.removeAll();
       panelAsian.repaint();
       panelAsian.revalidate();
       PaymentsForm PF=new PaymentsForm();
       PF.setSize(panelAsian.getSize());
       panelAsian.add(PF);
       panelAsian.repaint();
       panelAsian.revalidate();
               
    }//GEN-LAST:event_btnPaymentsActionPerformed

    private void btnTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherActionPerformed
        // TODO add your handling code here:
        panelAsian.removeAll();
        panelAsian.repaint();
        panelAsian.revalidate();
        TeacherForm TF=new TeacherForm();
        TF.setSize(panelAsian.getSize());
        panelAsian.add(TF);
        panelAsian.repaint();
        panelAsian.revalidate();
                
     
    }//GEN-LAST:event_btnTeacherActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        // TODO add your handling code here:
        panelAsian.removeAll();
        panelAsian.repaint();
        panelAsian.revalidate();
        ReportForm RF=new ReportForm();
        RF.setSize(panelAsian.getSize());
        panelAsian.add(RF);
        panelAsian.repaint();
        panelAsian.revalidate();
              
    }//GEN-LAST:event_btnReportsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DAteOn;
    private javax.swing.JButton btnAStudent;
    private javax.swing.JButton btnAttendance;
    private javax.swing.JButton btnExams;
    private javax.swing.JButton btnPayments;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnTeacher;
    private javax.swing.JButton btnVProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelAsian;
    // End of variables declaration//GEN-END:variables
 private void setDate() {
        Date d1=new Date();
        SimpleDateFormat fdate=new SimpleDateFormat("YYYY-MM-dd");
        String sd=fdate.format(d1);
       
        
        new Thread() {
            int timeRun=0;
            public void run() {
                while (timeRun == 0) {
                    Calendar cal = new GregorianCalendar();

                    int hour = cal.get(Calendar.HOUR_OF_DAY);
                    int min = cal.get(Calendar.MINUTE);
                    int AM_PM = cal.get(Calendar.AM_PM);

                    String day_night = "";
                    if (AM_PM == 1) {
                        day_night = "PM";
                    } else {
                        day_night = "AM";
                    }
                    String time = hour + ":" + min + " " + day_night;

                    DAteOn.setText(sd+"  "+time);
                     
                }
            }
        }.start();
    }

    private void setFullSreen() {
        Toolkit t = Toolkit.getDefaultToolkit();
        Dimension d = t.getScreenSize();
        this.setSize(d);
    }

    }
