/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.sms.view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author Chamini
 */
public class DashboadForm extends javax.swing.JFrame {

    /**
     * Creates new form Dashboad
     */
    public DashboadForm() {
        initComponents();
        setDate();
       setFullSreen();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DAteOn = new javax.swing.JLabel();
        btnAddStudent = new javax.swing.JButton();
        btnViewProfile = new javax.swing.JButton();
        btnExams = new javax.swing.JButton();
        btnAtendance = new javax.swing.JButton();
        btnPayments = new javax.swing.JButton();
        btnTeacher = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 160, 110);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel4.setText("Asian Higher Educational Center");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(380, 90, 710, 60);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel3.setText("Welcom To ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(610, 10, 290, 56);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/power.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1320, 10, 30, 30);

        DAteOn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DAteOn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(DAteOn);
        DAteOn.setBounds(1110, 50, 240, 30);

        btnAddStudent.setBackground(new java.awt.Color(0, 0, 10));
        btnAddStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/AddStudent.jpg"))); // NOI18N
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddStudent);
        btnAddStudent.setBounds(60, 200, 183, 209);

        btnViewProfile.setBackground(new java.awt.Color(0, 0, 10));
        btnViewProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/viewProfile.jpg"))); // NOI18N
        btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewProfile);
        btnViewProfile.setBounds(280, 200, 183, 209);

        btnExams.setBackground(new java.awt.Color(0, 0, 10));
        btnExams.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/examsmarks.jpg"))); // NOI18N
        btnExams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExamsActionPerformed(evt);
            }
        });
        jPanel1.add(btnExams);
        btnExams.setBounds(490, 200, 183, 209);

        btnAtendance.setBackground(new java.awt.Color(0, 0, 10));
        btnAtendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Attendnc1e.jpg"))); // NOI18N
        btnAtendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtendanceActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtendance);
        btnAtendance.setBounds(700, 200, 183, 209);

        btnPayments.setBackground(new java.awt.Color(0, 0, 10));
        btnPayments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/payments.jpg"))); // NOI18N
        btnPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentsActionPerformed(evt);
            }
        });
        jPanel1.add(btnPayments);
        btnPayments.setBounds(1140, 200, 183, 209);

        btnTeacher.setBackground(new java.awt.Color(0, 0, 10));
        btnTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/teacher.jpg"))); // NOI18N
        btnTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherActionPerformed(evt);
            }
        });
        jPanel1.add(btnTeacher);
        btnTeacher.setBounds(920, 200, 183, 209);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/settings.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(1290, 10, 25, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Reports.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(180, 430, 1030, 220);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1360, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        // TODO add your handling code here:
        AddStudentForm AF = new AddStudentForm("Add Student");
        AF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
        // TODO add your handling code here:
        AddStudentForm AF = new AddStudentForm("View Profile");
        AF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewProfileActionPerformed

    private void btnExamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExamsActionPerformed
        // TODO add your handling code here:
        AddStudentForm AF = new AddStudentForm("Exams");
        AF.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_btnExamsActionPerformed

    private void btnAtendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtendanceActionPerformed
        // TODO add your handling code here:
        AddStudentForm AF = new AddStudentForm("Attendense");
        AF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtendanceActionPerformed

    private void btnPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentsActionPerformed
        // TODO add your handling code here:
        AddStudentForm AF = new AddStudentForm("Payment");
        AF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPaymentsActionPerformed

    private void btnTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherActionPerformed
        // TODO add your handling code here:
        AddStudentForm AF = new AddStudentForm("Teacher");
        AF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTeacherActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        new Settings(this, true).setVisible(true);

    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AddStudentForm AF = new AddStudentForm("Reports");
        AF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboadForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DAteOn;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnAtendance;
    private javax.swing.JButton btnExams;
    private javax.swing.JButton btnPayments;
    private javax.swing.JButton btnTeacher;
    private javax.swing.JButton btnViewProfile;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
 private void setDate() {
        Date d1 = new Date();
        SimpleDateFormat fdate = new SimpleDateFormat("YYYY-MM-dd");
        String sd = fdate.format(d1);

        new Thread() {
            int timeRun = 0;

            public void run() {
                while (timeRun == 0) {
                    Calendar cal = new GregorianCalendar();

                    int hour = cal.get(Calendar.HOUR_OF_DAY);
                    int min = cal.get(Calendar.MINUTE);
                    int AM_PM = cal.get(Calendar.AM_PM);

                    String day_night = "";
                    if (AM_PM == 1) {
                        day_night = "PM";
                    } else {
                        day_night = "AM";
                    }
                    String time = hour + ":" + min + " " + day_night;

                    DAteOn.setText(sd + "  " + time);

                }
            }
        }.start();
    }

    private void setFullSreen() {
        Toolkit t = Toolkit.getDefaultToolkit();
        Dimension d = t.getScreenSize();
        this.setSize(d);
    }

}
