/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.sms.view;

import com.ijse.sms.controller.LoginController;
import com.ijse.sms.core.dto.LoginDTO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Chamini
 */
public class LogginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LogginForm() {
        initComponents();
       setLocationRelativeTo(null);
       txtuname.requestFocus();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbluname = new javax.swing.JLabel();
        lblpword = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        psword = new javax.swing.JPasswordField();
        lblasian = new javax.swing.JLabel();
        btnLog = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(687, 480));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("Login");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(430, 130, 150, 50);

        lbluname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbluname.setText("UserName");
        jPanel1.add(lbluname);
        lbluname.setBounds(440, 210, 100, 20);

        lblpword.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblpword.setText("Password");
        jPanel1.add(lblpword);
        lblpword.setBounds(440, 280, 100, 20);

        txtuname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunameActionPerformed(evt);
            }
        });
        jPanel1.add(txtuname);
        txtuname.setBounds(440, 240, 230, 30);

        psword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        psword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswordActionPerformed(evt);
            }
        });
        jPanel1.add(psword);
        psword.setBounds(440, 300, 230, 30);

        lblasian.setFont(new java.awt.Font("Chiller", 3, 48)); // NOI18N
        lblasian.setForeground(new java.awt.Color(4, 1, 23));
        lblasian.setText("ASIAN Higher Educational Center");
        jPanel1.add(lblasian);
        lblasian.setBounds(90, 10, 590, 60);

        btnLog.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLog.setText("LogIn");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });
        jPanel1.add(btnLog);
        btnLog.setBounds(570, 340, 100, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Foggot your Passowrd Or UserName");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(440, 380, 230, 17);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/new_homepage.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(687, 480));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 687, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunameActionPerformed
        // TODO add your handling code here:
        psword.requestFocus();
    }//GEN-LAST:event_txtunameActionPerformed

    private void pswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswordActionPerformed
        // TODO add your handling code here:
        btnLog.doClick();
    }//GEN-LAST:event_pswordActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
            String uname = txtuname.getText();
            String password = psword.getText();
            
            LoginDTO logid=new LoginDTO(uname,password);
        try {
            LoginDTO result = LoginController.search(logid);
            if(result!=null){
                String username = result.getUsername();
                String password1 = result.getPassword();
                
                if((username.equals(uname))&&(password1.equals(password))){
                    new DashboadForm().setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this,"Invalied UserName or Password.. Try Again!");
                    psword.setText("");
                    txtuname.requestFocus();
                }
            }else{
                JOptionPane.showMessageDialog(this,"User Name or password does not exisis....");
                psword.setText("");
                txtuname.requestFocus();
            }
        } catch (Exception ex) {
            Logger.getLogger(LogginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLogActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        new Settings(this, true).setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogginForm().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblasian;
    private javax.swing.JLabel lblpword;
    private javax.swing.JLabel lbluname;
    private javax.swing.JPasswordField psword;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables
}
