/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.sms.view;

/**
 *
 * @author Chamini
 */
public class ProfitForm extends javax.swing.JFrame {

    /**
     * Creates new form ProfitForm
     */
    public ProfitForm() {
        initComponents();
        setLocationRelativeTo(null);
          txtMIncon.setEnabled(false);
        txtMOut.setEnabled(false);
        txtMProfit.setEnabled(false);
        btnMPrint.setEnabled(false);
         txtYIncome.setEnabled(false);
        txtYOut.setEnabled(false);
        txtYProfit.setEnabled(false);
        btnYPrint.setEnabled(false);
        cmbMonth.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtdayIncom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAllProfit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRegFee = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTeacherPay = new javax.swing.JTextField();
        btnPrint = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbMonth = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        txtMIncon = new javax.swing.JTextField();
        txtMOut = new javax.swing.JTextField();
        txtMProfit = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnMPrint = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtYIncome = new javax.swing.JTextField();
        txtYOut = new javax.swing.JTextField();
        txtYProfit = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnYPrint = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        JDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Profit Report");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(300, 20, 220, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Profit / Lost");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(60, 80, 140, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Income Of The Day");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(60, 160, 120, 30);
        jPanel2.add(txtdayIncom);
        txtdayIncom.setBounds(200, 160, 260, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Profit / Loss Of The Day ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(110, 330, 160, 30);

        txtAllProfit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtAllProfit.setForeground(new java.awt.Color(102, 0, 0));
        jPanel2.add(txtAllProfit);
        txtAllProfit.setBounds(290, 330, 160, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Registration Fee");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(60, 200, 120, 30);
        jPanel2.add(txtRegFee);
        txtRegFee.setBounds(200, 200, 260, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Full Amount Of Teacher Payment");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(60, 240, 200, 30);
        jPanel2.add(txtTeacherPay);
        txtTeacherPay.setBounds(270, 240, 190, 30);

        btnPrint.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrint);
        btnPrint.setBounds(363, 390, 80, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel9.setText("Month Profit");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9);
        jLabel9.setBounds(540, 70, 120, 24);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Month");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(540, 110, 50, 17);

        cmbMonth.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jPanel2.add(cmbMonth);
        cmbMonth.setBounds(630, 110, 180, 23);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Income");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(540, 140, 43, 17);

        txtMIncon.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel2.add(txtMIncon);
        txtMIncon.setBounds(630, 140, 180, 23);

        txtMOut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel2.add(txtMOut);
        txtMOut.setBounds(630, 170, 180, 23);

        txtMProfit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtMProfit.setForeground(new java.awt.Color(153, 0, 0));
        jPanel2.add(txtMProfit);
        txtMProfit.setBounds(630, 200, 180, 28);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Profi / Loss");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(540, 200, 70, 17);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("OutGoing");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(540, 170, 60, 20);

        btnMPrint.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnMPrint.setText("Print");
        btnMPrint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(btnMPrint);
        btnMPrint.setBounds(750, 240, 90, 30);

        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel8);
        jLabel8.setBounds(520, 60, 340, 220);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel15.setText("Year Profit");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15);
        jLabel15.setBounds(530, 300, 110, 24);

        txtYIncome.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel2.add(txtYIncome);
        txtYIncome.setBounds(630, 360, 180, 23);

        txtYOut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel2.add(txtYOut);
        txtYOut.setBounds(630, 390, 180, 23);

        txtYProfit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtYProfit.setForeground(new java.awt.Color(153, 0, 0));
        jPanel2.add(txtYProfit);
        txtYProfit.setBounds(630, 420, 180, 28);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("Profi / Loss");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(540, 420, 70, 17);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("OutGoing");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(540, 390, 60, 20);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("Income");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(540, 360, 43, 17);

        btnYPrint.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnYPrint.setText("Print");
        btnYPrint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(btnYPrint);
        btnYPrint.setBounds(750, 460, 90, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(630, 320, 180, 30);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("Year");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(540, 330, 26, 20);

        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel14);
        jLabel14.setBounds(520, 290, 340, 210);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/power.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel19);
        jLabel19.setBounds(860, 10, 30, 30);
        jPanel2.add(JDate);
        JDate.setBounds(300, 120, 160, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        btnMPrint.setEnabled(true);
        txtMIncon.setEnabled(true);
        txtMOut.setEnabled(true);
        txtMProfit.setEnabled(true);
        cmbMonth.setEnabled(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        txtYIncome.setEnabled(true);
        txtYOut.setEnabled(true);
        txtYProfit.setEnabled(true);
        btnYPrint.setEnabled(true);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfitForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker JDate;
    private javax.swing.JButton btnMPrint;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnYPrint;
    private javax.swing.JComboBox cmbMonth;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAllProfit;
    private javax.swing.JTextField txtMIncon;
    private javax.swing.JTextField txtMOut;
    private javax.swing.JTextField txtMProfit;
    private javax.swing.JTextField txtRegFee;
    private javax.swing.JTextField txtTeacherPay;
    private javax.swing.JTextField txtYIncome;
    private javax.swing.JTextField txtYOut;
    private javax.swing.JTextField txtYProfit;
    private javax.swing.JTextField txtdayIncom;
    // End of variables declaration//GEN-END:variables
}
