/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.sms.view;

import com.ijse.sms.controller.ParentController;
import com.ijse.sms.controller.RegSubjectController;
import com.ijse.sms.controller.RegistrationController;
import com.ijse.sms.controller.StudentController;
import com.ijse.sms.core.dto.ParentDTO;
import com.ijse.sms.core.dto.RegSubjectDTO;
import com.ijse.sms.core.dto.RegistrationDTO;
import com.ijse.sms.core.dto.StudentDTO;
import com.ijse.sms.core.dto.SubjectDTO;
import com.ijse.sms.dao.db.DBConnection;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import lk.ijse.jasper.IJSEJasperViewer;
import lk.ijse.jasper.JasperUtil;
import lk.ijse.jasper.Report;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperReportsContext;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;

/**
 *
 * @author Chamini
 */
@Report("com.ijse.sms.reports")
public class StudentReportForm extends javax.swing.JFrame {

    /**
     * Creates new form StudentReportForm
     */
    public StudentReportForm() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblPRId = new javax.swing.JLabel();
        txtRid = new javax.swing.JTextField();
        lblPSId = new javax.swing.JLabel();
        txtStuId = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtStuName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPSchool = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPMobile = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPGrade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBday = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLevel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSubject = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setLayout(null);

        lblPRId.setBackground(new java.awt.Color(0, 51, 102));
        lblPRId.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblPRId.setText("Register ID");
        jPanel2.add(lblPRId);
        lblPRId.setBounds(40, 90, 80, 30);

        txtRid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtRid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRidActionPerformed(evt);
            }
        });
        jPanel2.add(txtRid);
        txtRid.setBounds(130, 90, 160, 30);

        lblPSId.setBackground(new java.awt.Color(0, 51, 102));
        lblPSId.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblPSId.setText("Student ID");
        jPanel2.add(lblPSId);
        lblPSId.setBounds(310, 90, 80, 30);

        txtStuId.setEditable(false);
        txtStuId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel2.add(txtStuId);
        txtStuId.setBounds(390, 90, 170, 30);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(20, 130, 550, 2);

        jLabel13.setBackground(new java.awt.Color(0, 51, 102));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setText("Name");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(40, 160, 80, 19);

        txtStuName.setEditable(false);
        txtStuName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtStuName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStuNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtStuName);
        txtStuName.setBounds(130, 150, 440, 30);

        jLabel2.setBackground(new java.awt.Color(0, 51, 102));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("Parent");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 200, 50, 19);

        txtPrName.setEditable(false);
        txtPrName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPrName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtPrName);
        txtPrName.setBounds(130, 193, 440, 30);

        jLabel3.setBackground(new java.awt.Color(0, 51, 102));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setText("Address");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 240, 60, 19);

        txtPAddress.setEditable(false);
        txtPAddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(txtPAddress);
        txtPAddress.setBounds(130, 233, 440, 30);

        jLabel4.setBackground(new java.awt.Color(0, 51, 102));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setText("School");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 280, 50, 19);

        txtPSchool.setEditable(false);
        txtPSchool.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(txtPSchool);
        txtPSchool.setBounds(130, 273, 440, 30);

        jLabel6.setBackground(new java.awt.Color(0, 51, 102));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("Mobile");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 320, 50, 19);

        txtPMobile.setEditable(false);
        txtPMobile.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPMobileKeyReleased(evt);
            }
        });
        jPanel2.add(txtPMobile);
        txtPMobile.setBounds(130, 313, 190, 30);

        jLabel10.setBackground(new java.awt.Color(0, 51, 102));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel10.setText("Grade");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(340, 320, 50, 20);

        txtPGrade.setEditable(false);
        txtPGrade.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(txtPGrade);
        txtPGrade.setBounds(400, 313, 170, 30);

        jLabel5.setBackground(new java.awt.Color(0, 51, 102));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("BirthDay");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 360, 70, 19);

        txtBday.setEditable(false);
        txtBday.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(txtBday);
        txtBday.setBounds(130, 353, 190, 30);

        jLabel9.setBackground(new java.awt.Color(0, 51, 102));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setText("Age");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(340, 360, 40, 19);

        txtAge.setEditable(false);
        txtAge.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(txtAge);
        txtAge.setBounds(400, 353, 170, 30);

        jLabel8.setBackground(new java.awt.Color(0, 51, 102));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("Gender");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(40, 390, 60, 30);

        txtGender.setEditable(false);
        txtGender.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        jPanel2.add(txtGender);
        txtGender.setBounds(130, 390, 190, 30);

        jLabel7.setBackground(new java.awt.Color(0, 51, 102));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("Level");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(340, 390, 40, 30);

        txtLevel.setEditable(false);
        txtLevel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(txtLevel);
        txtLevel.setBounds(400, 390, 170, 30);

        tblSubject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject ID", "Subject Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSubject);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(600, 70, 420, 150);

        jLabel11.setBackground(new java.awt.Color(0, 51, 102));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setText("Subjects");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(600, 40, 90, 19);

        btnPrint.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrint);
        btnPrint.setBounds(800, 460, 90, 30);

        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear);
        btnClear.setBounds(900, 460, 80, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton1.setText("Close");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(990, 460, 73, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.png"))); // NOI18N
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, 0, 1080, 510);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1078, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRidActionPerformed
        try {
            // TODO add your handling code here:
            String rid = txtRid.getText();
            //search details
            FillTable(rid);

        } catch (Exception ex) {
            Logger.getLogger(ViewProfileForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtRidActionPerformed

    private void txtStuNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStuNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStuNameActionPerformed

    private void txtPrNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrNameActionPerformed

    private void txtPMobileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPMobileKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPMobileKeyReleased

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
                JasperUtil.init(StudentReportForm.class);
                JasperReportsContext ctx = JasperUtil.getReportContext();
        
                try {
                        JasperReport compiledReport = JasperUtil.getCompiledReport("Students.jrxml");
                        JasperFillManager fillManager = JasperFillManager.getInstance(ctx);
                        HashMap<String, Object> reportParams = new HashMap<>();
                        reportParams.put("Reg_Id", txtRid.getText());
                      Connection connection=DBConnection.geBConnection().getConnection();
                        JasperPrint filledReport = fillManager.fill(compiledReport, reportParams,connection);
            
                        IJSEJasperViewer frmJSEJasperViewer = new IJSEJasperViewer(filledReport);
                        frmJSEJasperViewer.setTitle("Student Details");
                        frmJSEJasperViewer.setVisible(true);
                    } catch (JRException ex) {
                        Logger.getLogger(ViewProfileForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtAge.setText("");
        txtBday.setText("");
        txtGender.setText("");
        txtLevel.setText("");
        txtPAddress.setText("");
        txtPGrade.setText("");
        txtPMobile.setText("");
        txtPSchool.setText("");
        txtPrName.setText("");
        txtRid.setText("");
        txtStuId.setText("");
        txtStuName.setText("");
        clearTable();
    }//GEN-LAST:event_btnClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentReportForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblPRId;
    private javax.swing.JLabel lblPSId;
    public javax.swing.JTable tblSubject;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBday;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtPAddress;
    private javax.swing.JTextField txtPGrade;
    private javax.swing.JTextField txtPMobile;
    private javax.swing.JTextField txtPSchool;
    private javax.swing.JTextField txtPrName;
    private javax.swing.JTextField txtRid;
    private javax.swing.JTextField txtStuId;
    private javax.swing.JTextField txtStuName;
    // End of variables declaration//GEN-END:variables

 private void clearTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblSubject.getModel();
        dtm.setRowCount(0);
    }

    public void FillTable(String rid) throws Exception {
        RegistrationDTO registration = new RegistrationDTO(rid);
        RegistrationDTO search = RegistrationController.search(registration);
        System.out.println("regi ID : " + search.getReid());
//             registration.setGrade(search.getGrade());
        StudentDTO searchStudent = StudentController.searchEachStudent(search.getStuid());
        ParentDTO pr = new ParentDTO();
        pr.setPrId(searchStudent.getPid());
        ParentDTO searchparent = ParentController.searchparent(pr);

        txtStuId.setText(search.getReid());
        txtStuName.setText(searchStudent.getName());
        txtPrName.setText(searchparent.getPrName());
        txtPAddress.setText(searchStudent.getAddess());
        txtPSchool.setText(searchStudent.getSchool());
        txtPMobile.setText(searchStudent.getMobile() + "");
        txtGender.setText(searchStudent.getGender());
        txtAge.setText(searchStudent.getAge() + "");
        txtBday.setText(searchStudent.getDob());
        txtPGrade.setText(search.getGrade());

        RegSubjectDTO regSub = new RegSubjectDTO();
        regSub.setRSid(rid);
        System.out.println(rid);
        System.out.println(regSub);
        RegSubjectDTO search1 = RegSubjectController.search(regSub);
        System.out.println(search1);
        txtLevel.setText(search1.getRSLevel());

        ArrayList<SubjectDTO> all = RegSubjectController.eachSubjet(rid);
        DefaultTableModel dtm = (DefaultTableModel) tblSubject.getModel();
        dtm.setRowCount(0);
        for (SubjectDTO s : all) {
            dtm.addRow(new Object[]{s.getSubId(), s.getSubName()});
        }

    }

}
