/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.sms.view;

import com.ijse.sms.controller.ParentController;
import com.ijse.sms.controller.RegSubjectController;
import com.ijse.sms.controller.RegistrationController;
import com.ijse.sms.controller.StudentController;
import com.ijse.sms.core.dto.ParentDTO;
import com.ijse.sms.core.dto.RegSubjectDTO;
import com.ijse.sms.core.dto.RegistrationDTO;
import com.ijse.sms.core.dto.StudentDTO;
import com.ijse.sms.core.dto.SubjectDTO;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chamini
 */
public class ViewProfileForm extends javax.swing.JPanel {

    /**
     * Creates new form ViewProfileForm
     */
    public ViewProfileForm() {
        initComponents();
         txtRid.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPRId = new javax.swing.JLabel();
        txtRid = new javax.swing.JTextField();
        lblPSId = new javax.swing.JLabel();
        txtStuId = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtStuName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPSchool = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPMobile = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPGrade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBday = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLevel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSubject = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(null);

        lblPRId.setBackground(new java.awt.Color(0, 51, 102));
        lblPRId.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblPRId.setText("Register ID");
        jPanel1.add(lblPRId);
        lblPRId.setBounds(40, 90, 80, 30);

        txtRid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtRid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRidActionPerformed(evt);
            }
        });
        jPanel1.add(txtRid);
        txtRid.setBounds(130, 90, 160, 30);

        lblPSId.setBackground(new java.awt.Color(0, 51, 102));
        lblPSId.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblPSId.setText("Student ID");
        jPanel1.add(lblPSId);
        lblPSId.setBounds(310, 90, 80, 30);

        txtStuId.setEditable(false);
        txtStuId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(txtStuId);
        txtStuId.setBounds(390, 90, 170, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(20, 130, 550, 2);

        jLabel13.setBackground(new java.awt.Color(0, 51, 102));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setText("Name");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(40, 160, 80, 19);

        txtStuName.setEditable(false);
        txtStuName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtStuName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStuNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtStuName);
        txtStuName.setBounds(130, 150, 440, 30);

        jLabel2.setBackground(new java.awt.Color(0, 51, 102));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("Parent");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 200, 50, 19);

        txtPrName.setEditable(false);
        txtPrName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPrName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrName);
        txtPrName.setBounds(130, 193, 440, 30);

        jLabel3.setBackground(new java.awt.Color(0, 51, 102));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setText("Address");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 240, 60, 19);

        txtPAddress.setEditable(false);
        txtPAddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtPAddress);
        txtPAddress.setBounds(130, 233, 440, 30);

        jLabel4.setBackground(new java.awt.Color(0, 51, 102));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setText("School");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 280, 50, 19);

        txtPSchool.setEditable(false);
        txtPSchool.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtPSchool);
        txtPSchool.setBounds(130, 273, 440, 30);

        jLabel6.setBackground(new java.awt.Color(0, 51, 102));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("Mobile");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 320, 50, 19);

        txtPMobile.setEditable(false);
        txtPMobile.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPMobileKeyReleased(evt);
            }
        });
        jPanel1.add(txtPMobile);
        txtPMobile.setBounds(130, 313, 190, 30);

        jLabel10.setBackground(new java.awt.Color(0, 51, 102));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel10.setText("Grade");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(340, 320, 50, 20);

        txtPGrade.setEditable(false);
        txtPGrade.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtPGrade);
        txtPGrade.setBounds(400, 313, 170, 30);

        jLabel5.setBackground(new java.awt.Color(0, 51, 102));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("BirthDay");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 360, 70, 19);

        txtBday.setEditable(false);
        txtBday.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtBday);
        txtBday.setBounds(130, 353, 190, 30);

        jLabel9.setBackground(new java.awt.Color(0, 51, 102));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setText("Age");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(340, 360, 40, 19);

        txtAge.setEditable(false);
        txtAge.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtAge);
        txtAge.setBounds(400, 353, 170, 30);

        jLabel8.setBackground(new java.awt.Color(0, 51, 102));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 390, 60, 30);

        txtGender.setEditable(false);
        txtGender.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        jPanel1.add(txtGender);
        txtGender.setBounds(130, 390, 190, 30);

        jLabel7.setBackground(new java.awt.Color(0, 51, 102));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("Level");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(340, 390, 40, 30);

        txtLevel.setEditable(false);
        txtLevel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txtLevel);
        txtLevel.setBounds(400, 390, 170, 30);

        tblSubject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject ID", "Subject Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSubject);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(600, 100, 452, 340);

        jLabel11.setBackground(new java.awt.Color(0, 51, 102));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setText("Subjects");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(600, 70, 90, 19);

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);
        btnUpdate.setBounds(880, 480, 90, 30);

        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);
        btnClear.setBounds(980, 480, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1170, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1169, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRidActionPerformed
        try {
            // TODO add your handling code here:
            String rid = txtRid.getText();
            //search details
            FillTable(rid);

        } catch (Exception ex) {
            Logger.getLogger(ViewProfileForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtRidActionPerformed

    private void txtStuNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStuNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStuNameActionPerformed

    private void txtPrNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrNameActionPerformed

    private void txtPMobileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPMobileKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPMobileKeyReleased

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        UpdateStudentForm UF=new UpdateStudentForm(this);
        UF.setVisible(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtAge.setText("");
        txtBday.setText("");
        txtGender.setText("");
        txtLevel.setText("");
        txtPAddress.setText("");
        txtPGrade.setText("");
        txtPMobile.setText("");
        txtPSchool.setText("");
        txtPrName.setText("");
        txtRid.setText("");
        txtStuId.setText("");
        txtStuName.setText("");
        clearTable();

    }//GEN-LAST:event_btnClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblPRId;
    private javax.swing.JLabel lblPSId;
    public javax.swing.JTable tblSubject;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBday;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtPAddress;
    private javax.swing.JTextField txtPGrade;
    private javax.swing.JTextField txtPMobile;
    private javax.swing.JTextField txtPSchool;
    private javax.swing.JTextField txtPrName;
    private javax.swing.JTextField txtRid;
    private javax.swing.JTextField txtStuId;
    private javax.swing.JTextField txtStuName;
    // End of variables declaration//GEN-END:variables

   private void clearTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblSubject.getModel();
        dtm.setRowCount(0);
    }

    public void FillTable(String rid) throws Exception {
        RegistrationDTO registration = new RegistrationDTO(rid);
        RegistrationDTO search = RegistrationController.search(registration);
        System.out.println("regi ID : " + search.getReid());
//             registration.setGrade(search.getGrade());
        StudentDTO searchStudent = StudentController.searchEachStudent(search.getStuid());
        ParentDTO pr = new ParentDTO();
        pr.setPrId(searchStudent.getPid());
        ParentDTO searchparent = ParentController.searchparent(pr);

        txtStuId.setText(search.getStuid());
        txtStuName.setText(searchStudent.getName());
        txtPrName.setText(searchparent.getPrName());
        txtPAddress.setText(searchStudent.getAddess());
        txtPSchool.setText(searchStudent.getSchool());
        txtPMobile.setText(searchStudent.getMobile() + "");
        txtGender.setText(searchStudent.getGender());
        txtAge.setText(searchStudent.getAge() + "");
        txtBday.setText(searchStudent.getDob());
        txtPGrade.setText(search.getGrade());

        RegSubjectDTO regSub = new RegSubjectDTO();
        regSub.setRSid(rid);
        System.out.println(rid);
        System.out.println(regSub);
        RegSubjectDTO search1 = RegSubjectController.search(regSub);
        System.out.println(search1);
        txtLevel.setText(search1.getRSLevel());

        ArrayList<SubjectDTO> all = RegSubjectController.eachSubjet(rid);
        DefaultTableModel dtm = (DefaultTableModel) tblSubject.getModel();
        dtm.setRowCount(0);
        for (SubjectDTO s : all) {
            dtm.addRow(new Object[]{s.getSubId(), s.getSubName()});
        }

    }
}
